AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple_crud


Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: simple_crud/
      Handler: create.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
